version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    links:
      - redis
    ports:
      - 3000:3000
    networks:
      - app-network
  redis:
    image: redis:latest
    networks:
      - app-network
networks:
  app-network:
    driver: bridge